import type { Sport } from '@/types';

export interface TeamDef {
    id: string;
    name: string;       // Full name as returned by odds API
    city: string;       // City or school name (used for flexible matching)
    mascot: string;
    league: string;     // "NBA" | "NFL" | "NHL" | "MLB" | "NCAAB"
    sport: Sport;
    espnAbbr: string;   // ESPN CDN abbreviation or numeric ID (NCAAB)
}

export function teamLogoUrl(team: TeamDef): string {
    if (team.league === 'NCAAB') {
        return `https://a.espncdn.com/i/teamlogos/ncaa/500/${team.espnAbbr}.png`;
    }
    return `https://a.espncdn.com/i/teamlogos/${team.league.toLowerCase()}/500/${team.espnAbbr}.png`;
}

export function teamMatchesGame(team: TeamDef, gameTeamName: string): boolean {
    const g = gameTeamName.toLowerCase().trim();
    const name = team.name.toLowerCase();
    const city = team.city.toLowerCase();
    return g === name || g === city || g.startsWith(city + ' ') || name.startsWith(g + ' ') || g.includes(city);
}

export const ALL_TEAMS: TeamDef[] = [
    // ─── NBA ───────────────────────────────────────────────────────────────────
    { id: 'nba-atl', name: 'Atlanta Hawks',           city: 'Atlanta',       mascot: 'Hawks',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'atl' },
    { id: 'nba-bos', name: 'Boston Celtics',           city: 'Boston',        mascot: 'Celtics',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'bos' },
    { id: 'nba-bkn', name: 'Brooklyn Nets',            city: 'Brooklyn',      mascot: 'Nets',            league: 'NBA', sport: 'basketball_nba', espnAbbr: 'bkn' },
    { id: 'nba-cha', name: 'Charlotte Hornets',        city: 'Charlotte',     mascot: 'Hornets',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'cha' },
    { id: 'nba-chi', name: 'Chicago Bulls',            city: 'Chicago',       mascot: 'Bulls',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'chi' },
    { id: 'nba-cle', name: 'Cleveland Cavaliers',      city: 'Cleveland',     mascot: 'Cavaliers',       league: 'NBA', sport: 'basketball_nba', espnAbbr: 'cle' },
    { id: 'nba-dal', name: 'Dallas Mavericks',         city: 'Dallas',        mascot: 'Mavericks',       league: 'NBA', sport: 'basketball_nba', espnAbbr: 'dal' },
    { id: 'nba-den', name: 'Denver Nuggets',           city: 'Denver',        mascot: 'Nuggets',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'den' },
    { id: 'nba-det', name: 'Detroit Pistons',          city: 'Detroit',       mascot: 'Pistons',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'det' },
    { id: 'nba-gsw', name: 'Golden State Warriors',    city: 'Golden State',  mascot: 'Warriors',        league: 'NBA', sport: 'basketball_nba', espnAbbr: 'gs' },
    { id: 'nba-hou', name: 'Houston Rockets',          city: 'Houston',       mascot: 'Rockets',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'hou' },
    { id: 'nba-ind', name: 'Indiana Pacers',           city: 'Indiana',       mascot: 'Pacers',          league: 'NBA', sport: 'basketball_nba', espnAbbr: 'ind' },
    { id: 'nba-lac', name: 'Los Angeles Clippers',     city: 'Los Angeles',   mascot: 'Clippers',        league: 'NBA', sport: 'basketball_nba', espnAbbr: 'lac' },
    { id: 'nba-lal', name: 'Los Angeles Lakers',       city: 'Los Angeles',   mascot: 'Lakers',          league: 'NBA', sport: 'basketball_nba', espnAbbr: 'lal' },
    { id: 'nba-mem', name: 'Memphis Grizzlies',        city: 'Memphis',       mascot: 'Grizzlies',       league: 'NBA', sport: 'basketball_nba', espnAbbr: 'mem' },
    { id: 'nba-mia', name: 'Miami Heat',               city: 'Miami',         mascot: 'Heat',            league: 'NBA', sport: 'basketball_nba', espnAbbr: 'mia' },
    { id: 'nba-mil', name: 'Milwaukee Bucks',          city: 'Milwaukee',     mascot: 'Bucks',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'mil' },
    { id: 'nba-min', name: 'Minnesota Timberwolves',   city: 'Minnesota',     mascot: 'Timberwolves',    league: 'NBA', sport: 'basketball_nba', espnAbbr: 'min' },
    { id: 'nba-nop', name: 'New Orleans Pelicans',     city: 'New Orleans',   mascot: 'Pelicans',        league: 'NBA', sport: 'basketball_nba', espnAbbr: 'no' },
    { id: 'nba-nyk', name: 'New York Knicks',          city: 'New York',      mascot: 'Knicks',          league: 'NBA', sport: 'basketball_nba', espnAbbr: 'ny' },
    { id: 'nba-okc', name: 'Oklahoma City Thunder',    city: 'Oklahoma City', mascot: 'Thunder',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'okc' },
    { id: 'nba-orl', name: 'Orlando Magic',            city: 'Orlando',       mascot: 'Magic',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'orl' },
    { id: 'nba-phi', name: 'Philadelphia 76ers',       city: 'Philadelphia',  mascot: '76ers',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'phi' },
    { id: 'nba-phx', name: 'Phoenix Suns',             city: 'Phoenix',       mascot: 'Suns',            league: 'NBA', sport: 'basketball_nba', espnAbbr: 'phx' },
    { id: 'nba-por', name: 'Portland Trail Blazers',   city: 'Portland',      mascot: 'Trail Blazers',   league: 'NBA', sport: 'basketball_nba', espnAbbr: 'por' },
    { id: 'nba-sac', name: 'Sacramento Kings',         city: 'Sacramento',    mascot: 'Kings',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'sac' },
    { id: 'nba-sas', name: 'San Antonio Spurs',        city: 'San Antonio',   mascot: 'Spurs',           league: 'NBA', sport: 'basketball_nba', espnAbbr: 'sa' },
    { id: 'nba-tor', name: 'Toronto Raptors',          city: 'Toronto',       mascot: 'Raptors',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'tor' },
    { id: 'nba-uta', name: 'Utah Jazz',                city: 'Utah',          mascot: 'Jazz',            league: 'NBA', sport: 'basketball_nba', espnAbbr: 'utah' },
    { id: 'nba-was', name: 'Washington Wizards',       city: 'Washington',    mascot: 'Wizards',         league: 'NBA', sport: 'basketball_nba', espnAbbr: 'wsh' },

    // ─── NFL ───────────────────────────────────────────────────────────────────
    { id: 'nfl-ari', name: 'Arizona Cardinals',        city: 'Arizona',       mascot: 'Cardinals',       league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'ari' },
    { id: 'nfl-atl', name: 'Atlanta Falcons',          city: 'Atlanta',       mascot: 'Falcons',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'atl' },
    { id: 'nfl-bal', name: 'Baltimore Ravens',         city: 'Baltimore',     mascot: 'Ravens',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'bal' },
    { id: 'nfl-buf', name: 'Buffalo Bills',            city: 'Buffalo',       mascot: 'Bills',           league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'buf' },
    { id: 'nfl-car', name: 'Carolina Panthers',        city: 'Carolina',      mascot: 'Panthers',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'car' },
    { id: 'nfl-chi', name: 'Chicago Bears',            city: 'Chicago',       mascot: 'Bears',           league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'chi' },
    { id: 'nfl-cin', name: 'Cincinnati Bengals',       city: 'Cincinnati',    mascot: 'Bengals',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'cin' },
    { id: 'nfl-cle', name: 'Cleveland Browns',         city: 'Cleveland',     mascot: 'Browns',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'cle' },
    { id: 'nfl-dal', name: 'Dallas Cowboys',           city: 'Dallas',        mascot: 'Cowboys',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'dal' },
    { id: 'nfl-den', name: 'Denver Broncos',           city: 'Denver',        mascot: 'Broncos',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'den' },
    { id: 'nfl-det', name: 'Detroit Lions',            city: 'Detroit',       mascot: 'Lions',           league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'det' },
    { id: 'nfl-gb',  name: 'Green Bay Packers',        city: 'Green Bay',     mascot: 'Packers',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'gb' },
    { id: 'nfl-hou', name: 'Houston Texans',           city: 'Houston',       mascot: 'Texans',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'hou' },
    { id: 'nfl-ind', name: 'Indianapolis Colts',       city: 'Indianapolis',  mascot: 'Colts',           league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'ind' },
    { id: 'nfl-jax', name: 'Jacksonville Jaguars',     city: 'Jacksonville',  mascot: 'Jaguars',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'jax' },
    { id: 'nfl-kc',  name: 'Kansas City Chiefs',       city: 'Kansas City',   mascot: 'Chiefs',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'kc' },
    { id: 'nfl-lv',  name: 'Las Vegas Raiders',        city: 'Las Vegas',     mascot: 'Raiders',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'lv' },
    { id: 'nfl-lac', name: 'Los Angeles Chargers',     city: 'Los Angeles',   mascot: 'Chargers',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'lac' },
    { id: 'nfl-lar', name: 'Los Angeles Rams',         city: 'Los Angeles',   mascot: 'Rams',            league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'lar' },
    { id: 'nfl-mia', name: 'Miami Dolphins',           city: 'Miami',         mascot: 'Dolphins',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'mia' },
    { id: 'nfl-min', name: 'Minnesota Vikings',        city: 'Minnesota',     mascot: 'Vikings',         league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'min' },
    { id: 'nfl-ne',  name: 'New England Patriots',     city: 'New England',   mascot: 'Patriots',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'ne' },
    { id: 'nfl-no',  name: 'New Orleans Saints',       city: 'New Orleans',   mascot: 'Saints',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'no' },
    { id: 'nfl-nyg', name: 'New York Giants',          city: 'New York',      mascot: 'Giants',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'nyg' },
    { id: 'nfl-nyj', name: 'New York Jets',            city: 'New York',      mascot: 'Jets',            league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'nyj' },
    { id: 'nfl-phi', name: 'Philadelphia Eagles',      city: 'Philadelphia',  mascot: 'Eagles',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'phi' },
    { id: 'nfl-pit', name: 'Pittsburgh Steelers',      city: 'Pittsburgh',    mascot: 'Steelers',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'pit' },
    { id: 'nfl-sf',  name: 'San Francisco 49ers',      city: 'San Francisco', mascot: '49ers',           league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'sf' },
    { id: 'nfl-sea', name: 'Seattle Seahawks',         city: 'Seattle',       mascot: 'Seahawks',        league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'sea' },
    { id: 'nfl-tb',  name: 'Tampa Bay Buccaneers',     city: 'Tampa Bay',     mascot: 'Buccaneers',      league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'tb' },
    { id: 'nfl-ten', name: 'Tennessee Titans',         city: 'Tennessee',     mascot: 'Titans',          league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'ten' },
    { id: 'nfl-wsh', name: 'Washington Commanders',    city: 'Washington',    mascot: 'Commanders',      league: 'NFL', sport: 'americanfootball_nfl', espnAbbr: 'wsh' },

    // ─── NHL ───────────────────────────────────────────────────────────────────
    { id: 'nhl-ana', name: 'Anaheim Ducks',            city: 'Anaheim',       mascot: 'Ducks',           league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'ana' },
    { id: 'nhl-bos', name: 'Boston Bruins',            city: 'Boston',        mascot: 'Bruins',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'bos' },
    { id: 'nhl-buf', name: 'Buffalo Sabres',           city: 'Buffalo',       mascot: 'Sabres',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'buf' },
    { id: 'nhl-cgy', name: 'Calgary Flames',           city: 'Calgary',       mascot: 'Flames',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'cgy' },
    { id: 'nhl-car', name: 'Carolina Hurricanes',      city: 'Carolina',      mascot: 'Hurricanes',      league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'car' },
    { id: 'nhl-chi', name: 'Chicago Blackhawks',       city: 'Chicago',       mascot: 'Blackhawks',      league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'chi' },
    { id: 'nhl-col', name: 'Colorado Avalanche',       city: 'Colorado',      mascot: 'Avalanche',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'col' },
    { id: 'nhl-cbj', name: 'Columbus Blue Jackets',    city: 'Columbus',      mascot: 'Blue Jackets',    league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'cbj' },
    { id: 'nhl-dal', name: 'Dallas Stars',             city: 'Dallas',        mascot: 'Stars',           league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'dal' },
    { id: 'nhl-det', name: 'Detroit Red Wings',        city: 'Detroit',       mascot: 'Red Wings',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'det' },
    { id: 'nhl-edm', name: 'Edmonton Oilers',          city: 'Edmonton',      mascot: 'Oilers',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'edm' },
    { id: 'nhl-fla', name: 'Florida Panthers',         city: 'Florida',       mascot: 'Panthers',        league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'fla' },
    { id: 'nhl-lak', name: 'Los Angeles Kings',        city: 'Los Angeles',   mascot: 'Kings',           league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'la' },
    { id: 'nhl-min', name: 'Minnesota Wild',           city: 'Minnesota',     mascot: 'Wild',            league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'min' },
    { id: 'nhl-mtl', name: 'Montreal Canadiens',       city: 'Montreal',      mascot: 'Canadiens',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'mtl' },
    { id: 'nhl-nsh', name: 'Nashville Predators',      city: 'Nashville',     mascot: 'Predators',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'nsh' },
    { id: 'nhl-njd', name: 'New Jersey Devils',        city: 'New Jersey',    mascot: 'Devils',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'nj' },
    { id: 'nhl-nyi', name: 'New York Islanders',       city: 'New York',      mascot: 'Islanders',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'nyi' },
    { id: 'nhl-nyr', name: 'New York Rangers',         city: 'New York',      mascot: 'Rangers',         league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'nyr' },
    { id: 'nhl-ott', name: 'Ottawa Senators',          city: 'Ottawa',        mascot: 'Senators',        league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'ott' },
    { id: 'nhl-phi', name: 'Philadelphia Flyers',      city: 'Philadelphia',  mascot: 'Flyers',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'phi' },
    { id: 'nhl-pit', name: 'Pittsburgh Penguins',      city: 'Pittsburgh',    mascot: 'Penguins',        league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'pit' },
    { id: 'nhl-stl', name: 'St. Louis Blues',          city: 'St. Louis',     mascot: 'Blues',           league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'stl' },
    { id: 'nhl-sjs', name: 'San Jose Sharks',          city: 'San Jose',      mascot: 'Sharks',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'sj' },
    { id: 'nhl-sea', name: 'Seattle Kraken',           city: 'Seattle',       mascot: 'Kraken',          league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'sea' },
    { id: 'nhl-tbl', name: 'Tampa Bay Lightning',      city: 'Tampa Bay',     mascot: 'Lightning',       league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'tb' },
    { id: 'nhl-tor', name: 'Toronto Maple Leafs',      city: 'Toronto',       mascot: 'Maple Leafs',     league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'tor' },
    { id: 'nhl-uta', name: 'Utah Hockey Club',         city: 'Utah',          mascot: 'Hockey Club',     league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'utah' },
    { id: 'nhl-van', name: 'Vancouver Canucks',        city: 'Vancouver',     mascot: 'Canucks',         league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'van' },
    { id: 'nhl-vgk', name: 'Vegas Golden Knights',     city: 'Vegas',         mascot: 'Golden Knights',  league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'vgk' },
    { id: 'nhl-wsh', name: 'Washington Capitals',      city: 'Washington',    mascot: 'Capitals',        league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'wsh' },
    { id: 'nhl-wpg', name: 'Winnipeg Jets',            city: 'Winnipeg',      mascot: 'Jets',            league: 'NHL', sport: 'icehockey_nhl', espnAbbr: 'wpg' },

    // ─── MLB ───────────────────────────────────────────────────────────────────
    { id: 'mlb-ari', name: 'Arizona Diamondbacks',     city: 'Arizona',       mascot: 'Diamondbacks',    league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'ari' },
    { id: 'mlb-atl', name: 'Atlanta Braves',           city: 'Atlanta',       mascot: 'Braves',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'atl' },
    { id: 'mlb-bal', name: 'Baltimore Orioles',        city: 'Baltimore',     mascot: 'Orioles',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'bal' },
    { id: 'mlb-bos', name: 'Boston Red Sox',           city: 'Boston',        mascot: 'Red Sox',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'bos' },
    { id: 'mlb-chc', name: 'Chicago Cubs',             city: 'Chicago',       mascot: 'Cubs',            league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'chc' },
    { id: 'mlb-cws', name: 'Chicago White Sox',        city: 'Chicago',       mascot: 'White Sox',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'chw' },
    { id: 'mlb-cin', name: 'Cincinnati Reds',          city: 'Cincinnati',    mascot: 'Reds',            league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'cin' },
    { id: 'mlb-cle', name: 'Cleveland Guardians',      city: 'Cleveland',     mascot: 'Guardians',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'cle' },
    { id: 'mlb-col', name: 'Colorado Rockies',         city: 'Colorado',      mascot: 'Rockies',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'col' },
    { id: 'mlb-det', name: 'Detroit Tigers',           city: 'Detroit',       mascot: 'Tigers',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'det' },
    { id: 'mlb-hou', name: 'Houston Astros',           city: 'Houston',       mascot: 'Astros',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'hou' },
    { id: 'mlb-kc',  name: 'Kansas City Royals',       city: 'Kansas City',   mascot: 'Royals',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'kc' },
    { id: 'mlb-laa', name: 'Los Angeles Angels',       city: 'Los Angeles',   mascot: 'Angels',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'laa' },
    { id: 'mlb-lad', name: 'Los Angeles Dodgers',      city: 'Los Angeles',   mascot: 'Dodgers',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'lad' },
    { id: 'mlb-mia', name: 'Miami Marlins',            city: 'Miami',         mascot: 'Marlins',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'mia' },
    { id: 'mlb-mil', name: 'Milwaukee Brewers',        city: 'Milwaukee',     mascot: 'Brewers',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'mil' },
    { id: 'mlb-min', name: 'Minnesota Twins',          city: 'Minnesota',     mascot: 'Twins',           league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'min' },
    { id: 'mlb-nym', name: 'New York Mets',            city: 'New York',      mascot: 'Mets',            league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'nym' },
    { id: 'mlb-nyy', name: 'New York Yankees',         city: 'New York',      mascot: 'Yankees',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'nyy' },
    { id: 'mlb-oak', name: 'Athletics',                city: 'Oakland',       mascot: 'Athletics',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'oak' },
    { id: 'mlb-phi', name: 'Philadelphia Phillies',    city: 'Philadelphia',  mascot: 'Phillies',        league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'phi' },
    { id: 'mlb-pit', name: 'Pittsburgh Pirates',       city: 'Pittsburgh',    mascot: 'Pirates',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'pit' },
    { id: 'mlb-sd',  name: 'San Diego Padres',         city: 'San Diego',     mascot: 'Padres',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'sd' },
    { id: 'mlb-sf',  name: 'San Francisco Giants',     city: 'San Francisco', mascot: 'Giants',          league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'sf' },
    { id: 'mlb-sea', name: 'Seattle Mariners',         city: 'Seattle',       mascot: 'Mariners',        league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'sea' },
    { id: 'mlb-stl', name: 'St. Louis Cardinals',      city: 'St. Louis',     mascot: 'Cardinals',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'stl' },
    { id: 'mlb-tb',  name: 'Tampa Bay Rays',           city: 'Tampa Bay',     mascot: 'Rays',            league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'tb' },
    { id: 'mlb-tex', name: 'Texas Rangers',            city: 'Texas',         mascot: 'Rangers',         league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'tex' },
    { id: 'mlb-tor', name: 'Toronto Blue Jays',        city: 'Toronto',       mascot: 'Blue Jays',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'tor' },
    { id: 'mlb-wsh', name: 'Washington Nationals',     city: 'Washington',    mascot: 'Nationals',       league: 'MLB', sport: 'baseball_mlb', espnAbbr: 'wsh' },

    // ─── NCAAB — ACC ───────────────────────────────────────────────────────────
    { id: 'ncaa-bc',   name: 'Boston College Eagles',     city: 'Boston College', mascot: 'Eagles',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '103' },
    { id: 'ncaa-cal',  name: 'California Golden Bears',   city: 'California',     mascot: 'Golden Bears', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '25' },
    { id: 'ncaa-clem', name: 'Clemson Tigers',            city: 'Clemson',        mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '228' },
    { id: 'ncaa-duke', name: 'Duke Blue Devils',          city: 'Duke',           mascot: 'Blue Devils',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '150' },
    { id: 'ncaa-fsu',  name: 'Florida State Seminoles',   city: 'Florida State',  mascot: 'Seminoles',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '52' },
    { id: 'ncaa-gtech',name: 'Georgia Tech Yellow Jackets',city: 'Georgia Tech',  mascot: 'Yellow Jackets',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '59' },
    { id: 'ncaa-lou',  name: 'Louisville Cardinals',      city: 'Louisville',     mascot: 'Cardinals',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '97' },
    { id: 'ncaa-mia',  name: 'Miami Hurricanes',          city: 'Miami',          mascot: 'Hurricanes',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2390' },
    { id: 'ncaa-ncst', name: 'NC State Wolfpack',         city: 'NC State',       mascot: 'Wolfpack',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '152' },
    { id: 'ncaa-unc',  name: 'North Carolina Tar Heels',  city: 'North Carolina', mascot: 'Tar Heels',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '153' },
    { id: 'ncaa-nd',   name: 'Notre Dame Fighting Irish', city: 'Notre Dame',     mascot: 'Fighting Irish',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '87' },
    { id: 'ncaa-pitt', name: 'Pittsburgh Panthers',       city: 'Pittsburgh',     mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '221' },
    { id: 'ncaa-smu',  name: 'SMU Mustangs',              city: 'SMU',            mascot: 'Mustangs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2567' },
    { id: 'ncaa-stan', name: 'Stanford Cardinal',         city: 'Stanford',       mascot: 'Cardinal',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '24' },
    { id: 'ncaa-syr',  name: 'Syracuse Orange',           city: 'Syracuse',       mascot: 'Orange',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '183' },
    { id: 'ncaa-uva',  name: 'Virginia Cavaliers',        city: 'Virginia',       mascot: 'Cavaliers',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '258' },
    { id: 'ncaa-vt',   name: 'Virginia Tech Hokies',      city: 'Virginia Tech',  mascot: 'Hokies',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '259' },
    { id: 'ncaa-wake', name: 'Wake Forest Demon Deacons', city: 'Wake Forest',    mascot: 'Demon Deacons',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '154' },

    // ─── NCAAB — Big Ten ───────────────────────────────────────────────────────
    { id: 'ncaa-ill',  name: 'Illinois Fighting Illini',  city: 'Illinois',       mascot: 'Fighting Illini',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '356' },
    { id: 'ncaa-ind',  name: 'Indiana Hoosiers',          city: 'Indiana',        mascot: 'Hoosiers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '84' },
    { id: 'ncaa-iowa', name: 'Iowa Hawkeyes',             city: 'Iowa',           mascot: 'Hawkeyes',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2294' },
    { id: 'ncaa-umd',  name: 'Maryland Terrapins',        city: 'Maryland',       mascot: 'Terrapins',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '120' },
    { id: 'ncaa-mich', name: 'Michigan Wolverines',       city: 'Michigan',       mascot: 'Wolverines',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '130' },
    { id: 'ncaa-msu',  name: 'Michigan State Spartans',   city: 'Michigan State', mascot: 'Spartans',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '127' },
    { id: 'ncaa-minn', name: 'Minnesota Golden Gophers',  city: 'Minnesota',      mascot: 'Golden Gophers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '135' },
    { id: 'ncaa-neb',  name: 'Nebraska Cornhuskers',      city: 'Nebraska',       mascot: 'Cornhuskers',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '158' },
    { id: 'ncaa-nw',   name: 'Northwestern Wildcats',     city: 'Northwestern',   mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '77' },
    { id: 'ncaa-osu',  name: 'Ohio State Buckeyes',       city: 'Ohio State',     mascot: 'Buckeyes',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '194' },
    { id: 'ncaa-ore',  name: 'Oregon Ducks',              city: 'Oregon',         mascot: 'Ducks',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2483' },
    { id: 'ncaa-psu',  name: 'Penn State Nittany Lions',  city: 'Penn State',     mascot: 'Nittany Lions',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '213' },
    { id: 'ncaa-pur',  name: 'Purdue Boilermakers',       city: 'Purdue',         mascot: 'Boilermakers', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2509' },
    { id: 'ncaa-rug',  name: 'Rutgers Scarlet Knights',   city: 'Rutgers',        mascot: 'Scarlet Knights',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '164' },
    { id: 'ncaa-ucla', name: 'UCLA Bruins',               city: 'UCLA',           mascot: 'Bruins',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '26' },
    { id: 'ncaa-usc',  name: 'USC Trojans',               city: 'USC',            mascot: 'Trojans',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '30' },
    { id: 'ncaa-wash', name: 'Washington Huskies',        city: 'Washington',     mascot: 'Huskies',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '264' },
    { id: 'ncaa-wisc', name: 'Wisconsin Badgers',         city: 'Wisconsin',      mascot: 'Badgers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '275' },

    // ─── NCAAB — Big 12 ────────────────────────────────────────────────────────
    { id: 'ncaa-ariz', name: 'Arizona Wildcats',          city: 'Arizona',        mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '12' },
    { id: 'ncaa-asu',  name: 'Arizona State Sun Devils',  city: 'Arizona State',  mascot: 'Sun Devils',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '9' },
    { id: 'ncaa-bay',  name: 'Baylor Bears',              city: 'Baylor',         mascot: 'Bears',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '239' },
    { id: 'ncaa-byu',  name: 'BYU Cougars',              city: 'BYU',            mascot: 'Cougars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '252' },
    { id: 'ncaa-cin',  name: 'Cincinnati Bearcats',       city: 'Cincinnati',     mascot: 'Bearcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2132' },
    { id: 'ncaa-colo', name: 'Colorado Buffaloes',        city: 'Colorado',       mascot: 'Buffaloes',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '38' },
    { id: 'ncaa-hou',  name: 'Houston Cougars',           city: 'Houston',        mascot: 'Cougars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '248' },
    { id: 'ncaa-iast', name: 'Iowa State Cyclones',       city: 'Iowa State',     mascot: 'Cyclones',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '66' },
    { id: 'ncaa-kans', name: 'Kansas Jayhawks',           city: 'Kansas',         mascot: 'Jayhawks',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2305' },
    { id: 'ncaa-ksu',  name: 'Kansas State Wildcats',     city: 'Kansas State',   mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2306' },
    { id: 'ncaa-okst', name: 'Oklahoma State Cowboys',    city: 'Oklahoma State', mascot: 'Cowboys',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '197' },
    { id: 'ncaa-tcu',  name: 'TCU Horned Frogs',          city: 'TCU',            mascot: 'Horned Frogs', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2628' },
    { id: 'ncaa-tex',  name: 'Texas Longhorns',           city: 'Texas',          mascot: 'Longhorns',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '251' },
    { id: 'ncaa-ttu',  name: 'Texas Tech Red Raiders',    city: 'Texas Tech',     mascot: 'Red Raiders',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2641' },
    { id: 'ncaa-ucf',  name: 'UCF Knights',               city: 'UCF',            mascot: 'Knights',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2116' },
    { id: 'ncaa-utah', name: 'Utah Utes',                 city: 'Utah',           mascot: 'Utes',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '254' },
    { id: 'ncaa-wvu',  name: 'West Virginia Mountaineers',city: 'West Virginia',  mascot: 'Mountaineers', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '277' },

    // ─── NCAAB — SEC ───────────────────────────────────────────────────────────
    { id: 'ncaa-ala',  name: 'Alabama Crimson Tide',      city: 'Alabama',        mascot: 'Crimson Tide', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '333' },
    { id: 'ncaa-ark',  name: 'Arkansas Razorbacks',       city: 'Arkansas',       mascot: 'Razorbacks',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '8' },
    { id: 'ncaa-aub',  name: 'Auburn Tigers',             city: 'Auburn',         mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2' },
    { id: 'ncaa-fla',  name: 'Florida Gators',            city: 'Florida',        mascot: 'Gators',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '57' },
    { id: 'ncaa-uga',  name: 'Georgia Bulldogs',          city: 'Georgia',        mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '61' },
    { id: 'ncaa-uk',   name: 'Kentucky Wildcats',         city: 'Kentucky',       mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '96' },
    { id: 'ncaa-lsu',  name: 'LSU Tigers',                city: 'LSU',            mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '99' },
    { id: 'ncaa-msst', name: 'Mississippi State Bulldogs',city: 'Mississippi State',mascot: 'Bulldogs',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '344' },
    { id: 'ncaa-miz',  name: 'Missouri Tigers',           city: 'Missouri',       mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '142' },
    { id: 'ncaa-ole',  name: 'Ole Miss Rebels',           city: 'Ole Miss',       mascot: 'Rebels',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '145' },
    { id: 'ncaa-okla', name: 'Oklahoma Sooners',          city: 'Oklahoma',       mascot: 'Sooners',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '201' },
    { id: 'ncaa-scar', name: 'South Carolina Gamecocks',  city: 'South Carolina', mascot: 'Gamecocks',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2579' },
    { id: 'ncaa-tenn', name: 'Tennessee Volunteers',      city: 'Tennessee',      mascot: 'Volunteers',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2633' },
    { id: 'ncaa-tamu', name: 'Texas A&M Aggies',          city: 'Texas A&M',      mascot: 'Aggies',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '245' },
    { id: 'ncaa-vand', name: 'Vanderbilt Commodores',     city: 'Vanderbilt',     mascot: 'Commodores',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '238' },

    // ─── NCAAB — Big East ──────────────────────────────────────────────────────
    { id: 'ncaa-but',  name: 'Butler Bulldogs',           city: 'Butler',         mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2086' },
    { id: 'ncaa-cre',  name: 'Creighton Bluejays',        city: 'Creighton',      mascot: 'Bluejays',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '156' },
    { id: 'ncaa-dep',  name: 'DePaul Blue Demons',        city: 'DePaul',         mascot: 'Blue Demons',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '305' },
    { id: 'ncaa-geo',  name: 'Georgetown Hoyas',          city: 'Georgetown',     mascot: 'Hoyas',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '46' },
    { id: 'ncaa-mar',  name: 'Marquette Golden Eagles',   city: 'Marquette',      mascot: 'Golden Eagles',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '269' },
    { id: 'ncaa-pro',  name: 'Providence Friars',         city: 'Providence',     mascot: 'Friars',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2507' },
    { id: 'ncaa-shu',  name: 'Seton Hall Pirates',        city: 'Seton Hall',     mascot: 'Pirates',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2550' },
    { id: 'ncaa-sjn',  name: "St. John's Red Storm",      city: "St. John's",     mascot: 'Red Storm',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2596' },
    { id: 'ncaa-ucon', name: 'UConn Huskies',             city: 'UConn',          mascot: 'Huskies',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '41' },
    { id: 'ncaa-vil',  name: 'Villanova Wildcats',        city: 'Villanova',      mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '222' },
    { id: 'ncaa-xav',  name: 'Xavier Musketeers',         city: 'Xavier',         mascot: 'Musketeers',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2752' },

    // ─── NCAAB — American Athletic ─────────────────────────────────────────────
    { id: 'ncaa-char', name: 'Charlotte 49ers',           city: 'Charlotte',      mascot: '49ers',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2429' },
    { id: 'ncaa-ecu',  name: 'East Carolina Pirates',     city: 'East Carolina',  mascot: 'Pirates',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '151' },
    { id: 'ncaa-fau',  name: 'FAU Owls',                  city: 'FAU',            mascot: 'Owls',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2226' },
    { id: 'ncaa-mem',  name: 'Memphis Tigers',            city: 'Memphis',        mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '235' },
    { id: 'ncaa-unt',  name: 'North Texas Mean Green',    city: 'North Texas',    mascot: 'Mean Green',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '249' },
    { id: 'ncaa-rice', name: 'Rice Owls',                 city: 'Rice',           mascot: 'Owls',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '242' },
    { id: 'ncaa-usf',  name: 'South Florida Bulls',       city: 'South Florida',  mascot: 'Bulls',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '58' },
    { id: 'ncaa-tem',  name: 'Temple Owls',               city: 'Temple',         mascot: 'Owls',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '218' },
    { id: 'ncaa-tul',  name: 'Tulane Green Wave',         city: 'Tulane',         mascot: 'Green Wave',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2655' },
    { id: 'ncaa-tuls', name: 'Tulsa Golden Hurricane',    city: 'Tulsa',          mascot: 'Golden Hurricane',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '202' },
    { id: 'ncaa-uab',  name: 'UAB Blazers',               city: 'UAB',            mascot: 'Blazers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '392' },
    { id: 'ncaa-utsa', name: 'UTSA Roadrunners',          city: 'UTSA',           mascot: 'Roadrunners',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2636' },
    { id: 'ncaa-wst',  name: 'Wichita State Shockers',    city: 'Wichita State',  mascot: 'Shockers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2724' },

    // ─── NCAAB — Mountain West ─────────────────────────────────────────────────
    { id: 'ncaa-af',   name: 'Air Force Falcons',         city: 'Air Force',      mascot: 'Falcons',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2005' },
    { id: 'ncaa-bsu',  name: 'Boise State Broncos',       city: 'Boise State',    mascot: 'Broncos',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '68' },
    { id: 'ncaa-csu',  name: 'Colorado State Rams',       city: 'Colorado State', mascot: 'Rams',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '36' },
    { id: 'ncaa-fres', name: 'Fresno State Bulldogs',     city: 'Fresno State',   mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '278' },
    { id: 'ncaa-haw',  name: 'Hawaii Warriors',           city: 'Hawaii',         mascot: 'Warriors',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '62' },
    { id: 'ncaa-nev',  name: 'Nevada Wolf Pack',          city: 'Nevada',         mascot: 'Wolf Pack',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2440' },
    { id: 'ncaa-unm',  name: 'New Mexico Lobos',          city: 'New Mexico',     mascot: 'Lobos',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '167' },
    { id: 'ncaa-sdsu', name: 'San Diego State Aztecs',    city: 'San Diego State',mascot: 'Aztecs',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '21' },
    { id: 'ncaa-sjsu', name: 'San Jose State Spartans',   city: 'San Jose State', mascot: 'Spartans',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '23' },
    { id: 'ncaa-unlv', name: 'UNLV Rebels',               city: 'UNLV',           mascot: 'Rebels',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2439' },
    { id: 'ncaa-ust',  name: 'Utah State Aggies',         city: 'Utah State',     mascot: 'Aggies',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '328' },
    { id: 'ncaa-wyo',  name: 'Wyoming Cowboys',           city: 'Wyoming',        mascot: 'Cowboys',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2751' },

    // ─── NCAAB — WCC ───────────────────────────────────────────────────────────
    { id: 'ncaa-gonz', name: 'Gonzaga Bulldogs',          city: 'Gonzaga',        mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2250' },
    { id: 'ncaa-lmu',  name: 'LMU Lions',                 city: 'LMU',            mascot: 'Lions',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2339' },
    { id: 'ncaa-pepp', name: 'Pepperdine Waves',          city: 'Pepperdine',     mascot: 'Waves',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2736' },
    { id: 'ncaa-port', name: 'Portland Pilots',           city: 'Portland',       mascot: 'Pilots',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2502' },
    { id: 'ncaa-smc',  name: 'Saint Mary\'s Gaels',       city: "Saint Mary's",   mascot: 'Gaels',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2608' },
    { id: 'ncaa-sdieg',name: 'San Diego Toreros',         city: 'San Diego',      mascot: 'Toreros',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '301' },
    { id: 'ncaa-sfu',  name: 'San Francisco Dons',        city: 'San Francisco',  mascot: 'Dons',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2626' },
    { id: 'ncaa-scu',  name: 'Santa Clara Broncos',       city: 'Santa Clara',    mascot: 'Broncos',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2618' },
    { id: 'ncaa-pac',  name: 'Pacific Tigers',            city: 'Pacific',        mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2059' },

    // ─── NCAAB — Atlantic 10 ───────────────────────────────────────────────────
    { id: 'ncaa-day',  name: 'Dayton Flyers',             city: 'Dayton',         mascot: 'Flyers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2166' },
    { id: 'ncaa-dav',  name: 'Davidson Wildcats',         city: 'Davidson',       mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2168' },
    { id: 'ncaa-duq',  name: 'Duquesne Dukes',            city: 'Duquesne',       mascot: 'Dukes',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2184' },
    { id: 'ncaa-for',  name: 'Fordham Rams',              city: 'Fordham',        mascot: 'Rams',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2212' },
    { id: 'ncaa-gmu',  name: 'George Mason Patriots',     city: 'George Mason',   mascot: 'Patriots',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2244' },
    { id: 'ncaa-gwu',  name: 'George Washington Colonials',city: 'George Washington',mascot: 'Colonials', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '45' },
    { id: 'ncaa-las',  name: 'La Salle Explorers',        city: 'La Salle',       mascot: 'Explorers',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '312' },
    { id: 'ncaa-loy',  name: 'Loyola Chicago Ramblers',   city: 'Loyola Chicago', mascot: 'Ramblers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2710' },
    { id: 'ncaa-uma',  name: 'Massachusetts Minutemen',   city: 'Massachusetts',  mascot: 'Minutemen',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '113' },
    { id: 'ncaa-uri',  name: 'Rhode Island Rams',         city: 'Rhode Island',   mascot: 'Rams',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '227' },
    { id: 'ncaa-rich', name: 'Richmond Spiders',          city: 'Richmond',       mascot: 'Spiders',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '232' },
    { id: 'ncaa-sju',  name: "Saint Joseph's Hawks",      city: "Saint Joseph's", mascot: 'Hawks',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2603' },
    { id: 'ncaa-slu',  name: 'Saint Louis Billikens',     city: 'Saint Louis',    mascot: 'Billikens',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '139' },
    { id: 'ncaa-vcu',  name: 'VCU Rams',                  city: 'VCU',            mascot: 'Rams',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2670' },

    // ─── NCAAB — Missouri Valley ───────────────────────────────────────────────
    { id: 'ncaa-brad', name: 'Bradley Braves',            city: 'Bradley',        mascot: 'Braves',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '71' },
    { id: 'ncaa-drak', name: 'Drake Bulldogs',            city: 'Drake',          mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2181' },
    { id: 'ncaa-evan', name: 'Evansville Purple Aces',    city: 'Evansville',     mascot: 'Purple Aces',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '339' },
    { id: 'ncaa-ilst', name: 'Illinois State Redbirds',   city: 'Illinois State', mascot: 'Redbirds',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2210' },
    { id: 'ncaa-inst', name: 'Indiana State Sycamores',   city: 'Indiana State',  mascot: 'Sycamores',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2239' },
    { id: 'ncaa-murst',name: 'Murray State Racers',       city: 'Murray State',   mascot: 'Racers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '93' },
    { id: 'ncaa-most', name: 'Missouri State Bears',      city: 'Missouri State', mascot: 'Bears',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2623' },
    { id: 'ncaa-uni',  name: 'Northern Iowa Panthers',    city: 'Northern Iowa',  mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2460' },
    { id: 'ncaa-siu',  name: 'Southern Illinois Salukis', city: 'Southern Illinois',mascot: 'Salukis',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '79' },
    { id: 'ncaa-valp', name: 'Valparaiso Beacons',        city: 'Valparaiso',     mascot: 'Beacons',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2674' },

    // ─── NCAAB — MAC ───────────────────────────────────────────────────────────
    { id: 'ncaa-akr',  name: 'Akron Zips',                city: 'Akron',          mascot: 'Zips',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2006' },
    { id: 'ncaa-ball', name: 'Ball State Cardinals',       city: 'Ball State',     mascot: 'Cardinals',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2050' },
    { id: 'ncaa-bg',   name: 'Bowling Green Falcons',      city: 'Bowling Green',  mascot: 'Falcons',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '189' },
    { id: 'ncaa-buf',  name: 'Buffalo Bulls',             city: 'Buffalo',        mascot: 'Bulls',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2084' },
    { id: 'ncaa-cmu',  name: 'Central Michigan Chippewas',city: 'Central Michigan',mascot: 'Chippewas',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2117' },
    { id: 'ncaa-emu',  name: 'Eastern Michigan Eagles',   city: 'Eastern Michigan',mascot: 'Eagles',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2199' },
    { id: 'ncaa-kent', name: 'Kent State Golden Flashes',  city: 'Kent State',     mascot: 'Golden Flashes',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2309' },
    { id: 'ncaa-moh',  name: 'Miami Ohio Redhawks',       city: 'Miami Ohio',     mascot: 'Redhawks',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '193' },
    { id: 'ncaa-niu',  name: 'Northern Illinois Huskies', city: 'Northern Illinois',mascot: 'Huskies',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2459' },
    { id: 'ncaa-ohio', name: 'Ohio Bobcats',              city: 'Ohio',           mascot: 'Bobcats',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '195' },
    { id: 'ncaa-tol',  name: 'Toledo Rockets',            city: 'Toledo',         mascot: 'Rockets',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2649' },
    { id: 'ncaa-wmu',  name: 'Western Michigan Broncos',  city: 'Western Michigan',mascot: 'Broncos',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2711' },

    // ─── NCAAB — Sun Belt ──────────────────────────────────────────────────────
    { id: 'ncaa-apst', name: 'App State Mountaineers',    city: 'App State',      mascot: 'Mountaineers', league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2026' },
    { id: 'ncaa-arst', name: 'Arkansas State Red Wolves', city: 'Arkansas State', mascot: 'Red Wolves',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2032' },
    { id: 'ncaa-ccsu', name: 'Coastal Carolina Chanticleers',city: 'Coastal Carolina',mascot: 'Chanticleers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '324' },
    { id: 'ncaa-gast', name: 'Georgia Southern Eagles',   city: 'Georgia Southern',mascot: 'Eagles',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '290' },
    { id: 'ncaa-gast2',name: 'Georgia State Panthers',    city: 'Georgia State',  mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2247' },
    { id: 'ncaa-jst',  name: 'James Madison Dukes',       city: 'James Madison',  mascot: 'Dukes',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '256' },
    { id: 'ncaa-laf',  name: 'Louisiana Ragin Cajuns',    city: 'Louisiana',      mascot: "Ragin' Cajuns",league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '309' },
    { id: 'ncaa-lat',  name: 'Louisiana Tech Bulldogs',   city: 'Louisiana Tech', mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2348' },
    { id: 'ncaa-mardi',name: 'Marshall Thundering Herd',  city: 'Marshall',       mascot: 'Thundering Herd',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '276' },
    { id: 'ncaa-odu',  name: 'Old Dominion Monarchs',     city: 'Old Dominion',   mascot: 'Monarchs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '295' },
    { id: 'ncaa-sou',  name: 'Southern Miss Golden Eagles',city: 'Southern Miss', mascot: 'Golden Eagles',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2572' },
    { id: 'ncaa-troy', name: 'Troy Trojans',              city: 'Troy',           mascot: 'Trojans',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2653' },
    { id: 'ncaa-tex-st',name: 'Texas State Bobcats',      city: 'Texas State',    mascot: 'Bobcats',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '326' },
    { id: 'ncaa-slu2', name: 'South Alabama Jaguars',     city: 'South Alabama',  mascot: 'Jaguars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '6' },

    // ─── NCAAB — CUSA ──────────────────────────────────────────────────────────
    { id: 'ncaa-fiu',  name: 'FIU Panthers',              city: 'FIU',            mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2229' },
    { id: 'ncaa-lib',  name: 'Liberty Flames',            city: 'Liberty',        mascot: 'Flames',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2335' },
    { id: 'ncaa-mtsu', name: 'Middle Tennessee Blue Raiders',city: 'Middle Tennessee',mascot: 'Blue Raiders',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2393' },
    { id: 'ncaa-nmst', name: 'New Mexico State Aggies',   city: 'New Mexico State',mascot: 'Aggies',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '166' },
    { id: 'ncaa-samp', name: 'Samford Bulldogs',          city: 'Samford',        mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2565' },
    { id: 'ncaa-utep', name: 'UTEP Miners',               city: 'UTEP',           mascot: 'Miners',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2638' },
    { id: 'ncaa-wku',  name: 'Western Kentucky Hilltoppers',city: 'Western Kentucky',mascot: 'Hilltoppers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '98' },

    // ─── NCAAB — WAC ───────────────────────────────────────────────────────────
    { id: 'ncaa-gcu',  name: 'Grand Canyon Antelopes',    city: 'Grand Canyon',   mascot: 'Antelopes',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2253' },
    { id: 'ncaa-sfa',  name: 'Stephen F. Austin Lumberjacks',city: 'Stephen F. Austin',mascot: 'Lumberjacks',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2590' },
    { id: 'ncaa-tarlt',name: 'Tarleton State Texans',     city: 'Tarleton State', mascot: 'Texans',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2628' },
    { id: 'ncaa-utrgv',name: 'UT Rio Grande Valley Vaqueros',city: 'UTRGV',       mascot: 'Vaqueros',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '292' },

    // ─── NCAAB — Horizon ───────────────────────────────────────────────────────
    { id: 'ncaa-clev', name: 'Cleveland State Vikings',   city: 'Cleveland State',mascot: 'Vikings',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '325' },
    { id: 'ncaa-det2', name: 'Detroit Mercy Titans',      city: 'Detroit Mercy',  mascot: 'Titans',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2168' },
    { id: 'ncaa-iupui',name: 'IUPUI Jaguars',             city: 'IUPUI',          mascot: 'Jaguars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '85' },
    { id: 'ncaa-milw', name: 'Milwaukee Panthers',        city: 'Milwaukee',      mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '270' },
    { id: 'ncaa-nku',  name: 'Northern Kentucky Norse',   city: 'Northern Kentucky',mascot: 'Norse',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2467' },
    { id: 'ncaa-oaku', name: 'Oakland Golden Grizzlies',  city: 'Oakland',        mascot: 'Golden Grizzlies',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2337' },
    { id: 'ncaa-purfw',name: 'Purdue Fort Wayne Mastodons',city: 'Purdue Fort Wayne',mascot: 'Mastodons',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2870' },
    { id: 'ncaa-rmu',  name: 'Robert Morris Colonials',   city: 'Robert Morris',  mascot: 'Colonials',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2523' },
    { id: 'ncaa-wrst', name: 'Wright State Raiders',      city: 'Wright State',   mascot: 'Raiders',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2750' },
    { id: 'ncaa-ys',   name: 'Youngstown State Penguins', city: 'Youngstown State',mascot: 'Penguins',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2537' },

    // ─── NCAAB — Patriot ───────────────────────────────────────────────────────
    { id: 'ncaa-amer', name: 'American Eagles',           city: 'American',       mascot: 'Eagles',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '44' },
    { id: 'ncaa-army', name: 'Army Black Knights',        city: 'Army',           mascot: 'Black Knights',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '349' },
    { id: 'ncaa-buck', name: 'Bucknell Bison',            city: 'Bucknell',       mascot: 'Bison',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2083' },
    { id: 'ncaa-cg',   name: 'Colgate Raiders',           city: 'Colgate',        mascot: 'Raiders',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2142' },
    { id: 'ncaa-holy', name: 'Holy Cross Crusaders',      city: 'Holy Cross',     mascot: 'Crusaders',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '107' },
    { id: 'ncaa-laf2', name: 'Lafayette Leopards',        city: 'Lafayette',      mascot: 'Leopards',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '322' },
    { id: 'ncaa-leh',  name: 'Lehigh Mountain Hawks',     city: 'Lehigh',         mascot: 'Mountain Hawks',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2329' },
    { id: 'ncaa-navy', name: 'Navy Midshipmen',           city: 'Navy',           mascot: 'Midshipmen',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2426' },

    // ─── NCAAB — America East ──────────────────────────────────────────────────
    { id: 'ncaa-alb',  name: 'Albany Great Danes',        city: 'Albany',         mascot: 'Great Danes',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '399' },
    { id: 'ncaa-bngm', name: 'Binghamton Bearcats',       city: 'Binghamton',     mascot: 'Bearcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2066' },
    { id: 'ncaa-hart', name: 'Hartford Hawks',            city: 'Hartford',       mascot: 'Hawks',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '42' },
    { id: 'ncaa-main', name: 'Maine Black Bears',         city: 'Maine',          mascot: 'Black Bears',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '311' },
    { id: 'ncaa-md-bc',name: 'Maryland-Baltimore County Retrievers',city: 'UMBC', mascot: 'Retrievers',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2378' },
    { id: 'ncaa-nhmp', name: 'New Hampshire Wildcats',    city: 'New Hampshire',  mascot: 'Wildcats',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2350' },
    { id: 'ncaa-stony',name: 'Stony Brook Seawolves',     city: 'Stony Brook',    mascot: 'Seawolves',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2599' },
    { id: 'ncaa-uvm',  name: 'Vermont Catamounts',        city: 'Vermont',        mascot: 'Catamounts',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '261' },

    // ─── NCAAB — Big South ─────────────────────────────────────────────────────
    { id: 'ncaa-belm', name: 'Belmont Bruins',            city: 'Belmont',        mascot: 'Bruins',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2057' },
    { id: 'ncaa-camp', name: 'Campbell Fighting Camels',  city: 'Campbell',       mascot: 'Fighting Camels',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2097' },
    { id: 'ncaa-chso', name: 'Charleston Southern Buccaneers',city: 'Charleston Southern',mascot: 'Buccaneers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2127' },
    { id: 'ncaa-elon', name: 'Elon Phoenix',              city: 'Elon',           mascot: 'Phoenix',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2200' },
    { id: 'ncaa-hcu',  name: 'High Point Panthers',       city: 'High Point',     mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2261' },
    { id: 'ncaa-lond', name: 'Longwood Lancers',          city: 'Longwood',       mascot: 'Lancers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2344' },
    { id: 'ncaa-pres', name: 'Presbyterian Blue Hose',    city: 'Presbyterian',   mascot: 'Blue Hose',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2503' },
    { id: 'ncaa-rad',  name: 'Radford Highlanders',       city: 'Radford',        mascot: 'Highlanders',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2511' },
    { id: 'ncaa-uncas',name: 'UNC Asheville Bulldogs',    city: 'UNC Asheville',  mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2419' },

    // ─── NCAAB — Southern ──────────────────────────────────────────────────────
    { id: 'ncaa-chat', name: 'Chattanooga Mocs',          city: 'Chattanooga',    mascot: 'Mocs',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '236' },
    { id: 'ncaa-citad',name: 'The Citadel Bulldogs',      city: 'The Citadel',    mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2643' },
    { id: 'ncaa-etsu', name: 'East Tennessee State Buccaneers',city: 'ETSU',      mascot: 'Buccaneers',   league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2193' },
    { id: 'ncaa-fur',  name: 'Furman Paladins',           city: 'Furman',         mascot: 'Paladins',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '231' },
    { id: 'ncaa-mer',  name: 'Mercer Bears',              city: 'Mercer',         mascot: 'Bears',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2382' },
    { id: 'ncaa-sam',  name: 'Samford Bulldogs',          city: 'Samford',        mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2565' },
    { id: 'ncaa-unca2',name: 'UNC Greensboro Spartans',   city: 'UNC Greensboro', mascot: 'Spartans',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2421' },
    { id: 'ncaa-woff', name: 'Wofford Terriers',          city: 'Wofford',        mascot: 'Terriers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2749' },
    { id: 'ncaa-wcu',  name: 'Western Carolina Catamounts',city: 'Western Carolina',mascot: 'Catamounts',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2713' },

    // ─── NCAAB — OVC ───────────────────────────────────────────────────────────
    { id: 'ncaa-belmnt',name: 'Bellarmine Knights',       city: 'Bellarmine',     mascot: 'Knights',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2057' },
    { id: 'ncaa-ejkst',name: 'Eastern Kentucky Colonels', city: 'Eastern Kentucky',mascot: 'Colonels',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2198' },
    { id: 'ncaa-lipm', name: 'Lipscomb Bisons',           city: 'Lipscomb',       mascot: 'Bisons',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2340' },
    { id: 'ncaa-morhs',name: 'Morehead State Eagles',     city: 'Morehead State', mascot: 'Eagles',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2402' },
    { id: 'ncaa-semo', name: 'Southeast Missouri State Redhawks',city: 'Southeast Missouri State',mascot: 'Redhawks',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '116' },
    { id: 'ncaa-tenn-m',name: 'Tennessee-Martin Skyhawks',city: 'Tennessee-Martin',mascot: 'Skyhawks',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2635' },
    { id: 'ncaa-tst',  name: 'Tennessee State Tigers',    city: 'Tennessee State',mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2634' },
    { id: 'ncaa-ttech',name: 'Tennessee Tech Golden Eagles',city: 'Tennessee Tech',mascot: 'Golden Eagles',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2636' },

    // ─── NCAAB — Ivy League ────────────────────────────────────────────────────
    { id: 'ncaa-bro',  name: 'Brown Bears',               city: 'Brown',          mascot: 'Bears',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '225' },
    { id: 'ncaa-col',  name: 'Columbia Lions',            city: 'Columbia',       mascot: 'Lions',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '171' },
    { id: 'ncaa-corn', name: 'Cornell Big Red',           city: 'Cornell',        mascot: 'Big Red',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '172' },
    { id: 'ncaa-dart', name: 'Dartmouth Big Green',       city: 'Dartmouth',      mascot: 'Big Green',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '334' },
    { id: 'ncaa-harv', name: 'Harvard Crimson',           city: 'Harvard',        mascot: 'Crimson',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '108' },
    { id: 'ncaa-penn', name: 'Penn Quakers',              city: 'Penn',           mascot: 'Quakers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '219' },
    { id: 'ncaa-prin', name: 'Princeton Tigers',          city: 'Princeton',      mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '163' },
    { id: 'ncaa-yale', name: 'Yale Bulldogs',             city: 'Yale',           mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '43' },

    // ─── NCAAB — MAAC ──────────────────────────────────────────────────────────
    { id: 'ncaa-can',  name: 'Canisius Golden Griffins',  city: 'Canisius',       mascot: 'Golden Griffins',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2099' },
    { id: 'ncaa-fair', name: 'Fairfield Stags',           city: 'Fairfield',      mascot: 'Stags',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2210' },
    { id: 'ncaa-iona', name: 'Iona Gaels',                city: 'Iona',           mascot: 'Gaels',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '314' },
    { id: 'ncaa-man',  name: 'Manhattan Jaspers',         city: 'Manhattan',      mascot: 'Jaspers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2363' },
    { id: 'ncaa-marist',name: 'Marist Red Foxes',         city: 'Marist',         mascot: 'Red Foxes',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2369' },
    { id: 'ncaa-mont', name: 'Monmouth Hawks',            city: 'Monmouth',       mascot: 'Hawks',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2405' },
    { id: 'ncaa-niag', name: 'Niagara Purple Eagles',     city: 'Niagara',        mascot: 'Purple Eagles',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '315' },
    { id: 'ncaa-que',  name: 'Quinnipiac Bobcats',        city: 'Quinnipiac',     mascot: 'Bobcats',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2509' },
    { id: 'ncaa-rider',name: 'Rider Broncs',              city: 'Rider',          mascot: 'Broncs',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2520' },
    { id: 'ncaa-siena',name: 'Siena Saints',              city: 'Siena',          mascot: 'Saints',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2561' },

    // ─── NCAAB — CAA ───────────────────────────────────────────────────────────
    { id: 'ncaa-chco', name: 'Charleston Cougars',        city: 'Charleston',     mascot: 'Cougars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '232' },
    { id: 'ncaa-del',  name: 'Delaware Fightin Blue Hens',city: 'Delaware',       mascot: 'Fightin Blue Hens',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2197' },
    { id: 'ncaa-drex', name: 'Drexel Dragons',            city: 'Drexel',         mascot: 'Dragons',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2182' },
    { id: 'ncaa-hofst',name: 'Hofstra Pride',             city: 'Hofstra',        mascot: 'Pride',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2264' },
    { id: 'ncaa-neast',name: 'Northeastern Huskies',      city: 'Northeastern',   mascot: 'Huskies',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '111' },
    { id: 'ncaa-tows', name: 'Towson Tigers',             city: 'Towson',         mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2651' },
    { id: 'ncaa-wm',   name: 'William & Mary Tribe',      city: 'William & Mary', mascot: 'Tribe',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2729' },
    { id: 'ncaa-unco', name: 'UNC Wilmington Seahawks',   city: 'UNC Wilmington', mascot: 'Seahawks',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2423' },

    // ─── NCAAB — SWAC ──────────────────────────────────────────────────────────
    { id: 'ncaa-alama',name: 'Alabama A&M Bulldogs',      city: 'Alabama A&M',    mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2010' },
    { id: 'ncaa-alst', name: 'Alabama State Hornets',     city: 'Alabama State',  mascot: 'Hornets',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2011' },
    { id: 'ncaa-alcor',name: 'Alcorn State Braves',       city: 'Alcorn State',   mascot: 'Braves',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2013' },
    { id: 'ncaa-arpin',name: 'Arkansas-Pine Bluff Golden Lions',city: 'Arkansas-Pine Bluff',mascot: 'Golden Lions',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2031' },
    { id: 'ncaa-gram', name: 'Grambling State Tigers',    city: 'Grambling State',mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2755' },
    { id: 'ncaa-jkst', name: 'Jackson State Tigers',      city: 'Jackson State',  mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2296' },
    { id: 'ncaa-mvst', name: 'Mississippi Valley State Delta Devils',city: 'Mississippi Valley State',mascot: 'Delta Devils',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2397' },
    { id: 'ncaa-prair',name: 'Prairie View A&M Panthers', city: 'Prairie View A&M',mascot: 'Panthers',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2504' },
    { id: 'ncaa-subrd',name: 'Southern Jaguars',          city: 'Southern',       mascot: 'Jaguars',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2582' },
    { id: 'ncaa-texso',name: 'Texas Southern Tigers',     city: 'Texas Southern', mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2640' },

    // ─── NCAAB — MEAC ──────────────────────────────────────────────────────────
    { id: 'ncaa-bowa', name: 'Bowie State Bulldogs',      city: 'Bowie State',    mascot: 'Bulldogs',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2079' },
    { id: 'ncaa-copst',name: 'Coppin State Eagles',       city: 'Coppin State',   mascot: 'Eagles',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2154' },
    { id: 'ncaa-dcs',  name: 'Delaware State Hornets',    city: 'Delaware State', mascot: 'Hornets',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2196' },
    { id: 'ncaa-hampt',name: 'Hampton Pirates',           city: 'Hampton',        mascot: 'Pirates',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2261' },
    { id: 'ncaa-howa', name: 'Howard Bison',              city: 'Howard',         mascot: 'Bison',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '47' },
    { id: 'ncaa-mdest',name: 'Maryland-Eastern Shore Hawks',city: 'Maryland-Eastern Shore',mascot: 'Hawks',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2379' },
    { id: 'ncaa-morg', name: 'Morgan State Bears',        city: 'Morgan State',   mascot: 'Bears',        league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2405' },
    { id: 'ncaa-ncca', name: 'NC A&T Aggies',             city: 'NC A&T',         mascot: 'Aggies',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2427' },
    { id: 'ncaa-norfs',name: 'Norfolk State Spartans',    city: 'Norfolk State',  mascot: 'Spartans',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2450' },
    { id: 'ncaa-savst',name: 'Savannah State Tigers',     city: 'Savannah State', mascot: 'Tigers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2554' },
    { id: 'ncaa-scar2',name: 'South Carolina State Bulldogs',city: 'South Carolina State',mascot: 'Bulldogs',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2580' },

    // ─── NCAAB — Big West ──────────────────────────────────────────────────────
    { id: 'ncaa-csb',  name: 'Cal State Bakersfield Roadrunners',city: 'Cal State Bakersfield',mascot: 'Roadrunners',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2087' },
    { id: 'ncaa-csf',  name: 'Cal State Fullerton Titans', city: 'Cal State Fullerton',mascot: 'Titans',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2104' },
    { id: 'ncaa-csn',  name: 'Cal State Northridge Matadors',city: 'Cal State Northridge',mascot: 'Matadors',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2111' },
    { id: 'ncaa-cslong',name: 'Long Beach State 49ers',   city: 'Long Beach State',mascot: '49ers',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2342' },
    { id: 'ncaa-ucd',  name: 'UC Davis Aggies',           city: 'UC Davis',       mascot: 'Aggies',       league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2102' },
    { id: 'ncaa-uci',  name: 'UC Irvine Anteaters',       city: 'UC Irvine',      mascot: 'Anteaters',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2103' },
    { id: 'ncaa-ucriv',name: 'UC Riverside Highlanders',  city: 'UC Riverside',   mascot: 'Highlanders',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2105' },
    { id: 'ncaa-ucsb', name: 'UC Santa Barbara Gauchos',  city: 'UC Santa Barbara',mascot: 'Gauchos',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2101' },

    // ─── NCAAB — Northeast ─────────────────────────────────────────────────────
    { id: 'ncaa-ccny', name: 'Central Connecticut Blue Devils',city: 'Central Connecticut',mascot: 'Blue Devils',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2115' },
    { id: 'ncaa-fairl',name: 'Fairleigh Dickinson Knights',city: 'Fairleigh Dickinson',mascot: 'Knights',  league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2214' },
    { id: 'ncaa-lmu2', name: 'Long Island University Sharks',city: 'LIU',          mascot: 'Sharks',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2343' },
    { id: 'ncaa-merr', name: 'Merrimack Warriors',        city: 'Merrimack',      mascot: 'Warriors',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2384' },
    { id: 'ncaa-mont2',name: 'Mount St. Mary\'s Mountaineers',city: 'Mount St. Mary\'s',mascot: 'Mountaineers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '116' },
    { id: 'ncaa-scu2', name: 'Sacred Heart Pioneers',     city: 'Sacred Heart',   mascot: 'Pioneers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2557' },
    { id: 'ncaa-shu2', name: 'St. Francis Brooklyn Terriers',city: 'St. Francis Brooklyn',mascot: 'Terriers',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2597' },
    { id: 'ncaa-wag',  name: 'Wagner Seahawks',           city: 'Wagner',         mascot: 'Seahawks',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2681' },

    // ─── NCAAB — Independent / Other ──────────────────────────────────────────
    { id: 'ncaa-oral', name: 'Oral Roberts Golden Eagles',city: 'Oral Roberts',   mascot: 'Golden Eagles',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '198' },
    { id: 'ncaa-sbe',  name: 'South Dakota State Jackrabbits',city: 'South Dakota State',mascot: 'Jackrabbits',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2571' },
    { id: 'ncaa-sdak', name: 'South Dakota Coyotes',      city: 'South Dakota',   mascot: 'Coyotes',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2569' },
    { id: 'ncaa-ndak', name: 'North Dakota State Bison',  city: 'North Dakota State',mascot: 'Bison',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2449' },
    { id: 'ncaa-noda', name: 'North Dakota Fighting Hawks',city: 'North Dakota',   mascot: 'Fighting Hawks',league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2446' },
    { id: 'ncaa-umkc', name: 'Kansas City Roos',          city: 'Kansas City',    mascot: 'Roos',         league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2308' },
    { id: 'ncaa-wis-m',name: 'Milwaukee Panthers',        city: 'UW-Milwaukee',   mascot: 'Panthers',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '270' },
    { id: 'ncaa-nbg',  name: 'Northern Colorado Bears',   city: 'Northern Colorado',mascot: 'Bears',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2458' },
    { id: 'ncaa-porst',name: 'Portland State Vikings',    city: 'Portland State', mascot: 'Vikings',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2501' },
    { id: 'ncaa-sac-s',name: 'Sacramento State Hornets',  city: 'Sacramento State',mascot: 'Hornets',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '16' },
    { id: 'ncaa-mont3',name: 'Montana Grizzlies',         city: 'Montana',        mascot: 'Grizzlies',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '149' },
    { id: 'ncaa-monts',name: 'Montana State Bobcats',     city: 'Montana State',  mascot: 'Bobcats',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '147' },
    { id: 'ncaa-ebay', name: 'Eastern Washington Eagles', city: 'Eastern Washington',mascot: 'Eagles',    league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '331' },
    { id: 'ncaa-idho', name: 'Idaho Vandals',             city: 'Idaho',          mascot: 'Vandals',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '70' },
    { id: 'ncaa-idst', name: 'Idaho State Bengals',       city: 'Idaho State',    mascot: 'Bengals',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '304' },
    { id: 'ncaa-nev-l',name: 'Nevada-Las Vegas Rebels',   city: 'Nevada-Las Vegas',mascot: 'Rebels',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '2439' },
    { id: 'ncaa-orst', name: 'Oregon State Beavers',      city: 'Oregon State',   mascot: 'Beavers',      league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '204' },
    { id: 'ncaa-wast', name: 'Washington State Cougars',  city: 'Washington State',mascot: 'Cougars',     league: 'NCAAB', sport: 'basketball_ncaab', espnAbbr: '265' },
];
